theme: jekyll-theme-minimal
title: Brian Hudi
description: Developer, Blogger, Speaker
repository: hudibrian/hudibrian.github.io
domain: brianhudi.com
author: Brian Hudi
email: bshudi@gmail.com
github: https://www.github.com/hudibrian
twitter: https://www.twitter.com/brianhudi
linkedin: https://www.linkedin.com/in/brian-hudi-73256632/
blog: https://www.brianhudi.org
baseurl: /hudibrian.github.io